### PR TITLE
Ignore the dll files.

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by lochel** [comment]
I think the dll actually shouldn't show up. So maybe we could fix the build instructions instead.

**Comment by adeas31** [comment]
That would be even better.

**Comment by adeas31** [comment]
Well I am not sure if we can skip dll after reading this from Lua docs,

> To use Lua as a library in your own programs you'll need to know how to create and use libraries with your compiler. Moreover, to dynamically load C libraries for Lua you'll need to know how to create dynamic libraries and you'll need to make sure that the Lua API functions are accessible to those dynamic libraries — but don't link the Lua library into each dynamic library. For Unix, we recommend that the Lua library be linked statically into the host program and its symbols exported for dynamic linking; src/Makefile does this for the Lua interpreter. For Windows, we recommend that the Lua library be a DLL. In all cases, the compiler luac should be linked statically.

I saw that we only move the static library to install folder.

**Comment by adeas31** [comment]
@lochel can you test this for Linux? I am not sure if `.so` is generated there or not.

**Comment by lochel** [comment]
There is no `lua53.so` on Linux.

**Pull request merged**
